import React from 'react';
import { Check, Plus, Sparkles } from 'lucide-react';
import './agent-provider-manager.css';
import type { AgentRuntime, Role } from './lib/profile-api';

type Gateway = { status: 'loading' | 'bridge_offline' | 'not_configured' | 'unknown' | 'offline' | 'online' };

export function AgentProviderManager({ roles, gateway, runtimes, setRoute, add }: { roles: Role[]; gateway: Gateway; runtimes: Record<string, AgentRuntime>; setRoute: (id: string, provider: string, model: string) => void; add: () => void }) {
  const update = (id: string, field: keyof AgentRuntime, value: string) => { const current = runtimes[id] || { provider: '', model: '' }; setRoute(id, field === 'provider' ? value : current.provider, field === 'model' ? value : current.model); };
  return <div className="page agent-provider-page"><div className="page-header"><div><h1>Agents</h1><p>Set a provider and model per agent. Each agent’s run uses only its own route.</p></div><div className="page-actions"><button className="button button-secondary" onClick={add}><Plus size={14} /> Add agent</button></div></div><section className="agent-provider-intro"><Sparkles size={18} /><p>Provider and model overrides are submitted to Hermes on each run. A blank field uses the verified gateway default; changing one agent never changes another.</p></section><section className="agent-provider-table" aria-label="Agent provider routing"><header><span>Agent</span><span>Responsibility</span><span>Provider</span><span>Model</span><span>Route</span></header>{roles.map(role => { const runtime = runtimes[role.id] || { provider: '', model: '' }; const configured = Boolean(runtime.provider || runtime.model); return <div className="agent-provider-row" key={role.id}><div className="agent-cell"><span className="avatar">{role.initials}</span><strong>{role.name}</strong></div><span className="agent-provider-role">{role.role}</span><label><span className="sr-only">Provider for {role.name}</span><input value={runtime.provider} onChange={event => update(role.id, 'provider', event.target.value)} placeholder="Gateway default" autoCapitalize="none" /></label><label><span className="sr-only">Model for {role.name}</span><input value={runtime.model} onChange={event => update(role.id, 'model', event.target.value)} placeholder="Gateway default" autoCapitalize="none" /></label><span className={`agent-route-status ${configured ? 'configured' : ''}`}>{configured ? <><Check size={13} /> Per-agent route</> : gateway.status === 'online' ? 'Gateway default' : 'Runtime offline'}</span></div>; })}{!roles.length && <div className="compact-empty"><strong>No agents yet</strong><p>Create an agent before assigning its own provider and model.</p></div>}</section></div>;
}
